language: java
jdk:
- oraclejdk7
script: mvn clean package
install: true
notifications:
  email:
    recipients:
    - ybrin.development@gmail.com
    - simon.artner@gmail.com
    on_success: change
    on_failure: always
  webhooks: https://api.kwstudios.org/travis/webhooks/versions
before_deploy:
- ls
- cd target/
- ls
- cd ..
deploy:
  provider: gcs
  access_key_id: GOOGOORZ55TL3TFGHJHZ
  secret_access_key:
    secure: ewxMQArrYG2TrfgYLc9PYPl4i8BM7qa1UQthE1u3MHyp4H7CkxcLmpUrVh9M6eCqmrlTgHDReoe+OBCMbgxzYrmO+Jh3IyQapC0d0QTxEOo9oojb7E3nodtF2EEtEFa3rRWlm/tLeraK+FD9qxmTn5+w1Mg1fEQghdikuXoPOsoBVRBBx5VcG0MIeaPwDgs0YVTCpqlGyYtwO89X1RCtobYyGVqgg6nAUq8CSchKyV+7fpvm2OfjIo5HPRwGRnk/Xk8l/RFzBmEmWxDB7hGvQFVtXFND+pgHsyiKM1eTZMxVSDyIqJCP82+VvbbiXtJ51891+4HomMUarmj0qAjRIxhpyF65/pWhfIwWJi0oHA3QRzR48hPo3iOfSeacR7oJmV5Yu2dRHQu08Plvdh+cZRuLDIZsjzgWnsRI3ld21qlpiEdm3R/NRc5ER2hgykWvnOYVnu5UWP4Yyqmfg5ESzRO5s6gylGG3kBaDbHM1aFUSUTGR+EBT65s5k8zUKJvGlGjprQeGnhKtkY6yhxBAL6MqbfJavWQMxggwy54WHZafNGkSbA31DRUJGOtFFnPZgvpUyHDCjt9Dp7fqeGWFhuLB314niyc4GG2Kgh/hRbXs1E/5t6eropSVtL2Pt33ZOFc2cQTPtwVWFP7DFc7e1qoaLmdkwHsRvMcizZwBKHU=
  file_glob: true
  bucket: kwstudios-main-bucket
  local-dir: ${HOME}/build/${TRAVIS_REPO_SLUG}/target
  upload-dir: travis/kwbungeelobby/${TRAVIS_BUILD_NUMBER}
  skip_cleanup: true
  acl: public-read
  on:
    repo: KWStudios/KWBungeeMinigame
